[[redirects]]
  from = "/mars-randomizer/"
  to = "https://projects.sia.codes/mars-randomizer/"
[[redirects]]
  from = "/posts/prettier/"
  to = "/posts/how-to-add-prettier-to-a-project/"
[[redirects]]
  from = "/posts/wow-look-at-this-number-input/"
  to = "/posts/how-to-build-a-website/"
[[plugins]]
  package = "netlify-plugin-cache-folder"
[build.processing]
  skip_processing = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
