[[plugins]]
  package = "netlify-plugin-cache-folder"
[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[build.processing]
  skip_processing = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[dev]
  command = "npm run dev"
